### ISSUE TITLE
update-aliases is working?

### ISSUE THREAD

**Issue by Rakk4403** [tommoor/react-emoji-render#111]
I got a clone and just did `yarn install` and `yarn update-aliases`,

```shell
➜  react-emoji-render git:(master) ✗ yarn update-aliases
yarn run v1.22.19
$ node tasks/parse.js && node tasks/merge.js && node tasks/validate.js

***PARSE***
Running => /parse/baseAliases.js
node:internal/fs/utils:348
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/chris-noul/workspace/react-emoji-render/data/raw/baseAliases.json'
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at Object.<anonymous> (/Users/chris-noul/workspace/react-emoji-render/scripts/parse/baseAliases.js:9:6)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/chris-noul/workspace/react-emoji-render/tasks/parse.js:18:5 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/chris-noul/workspace/react-emoji-render/data/raw/baseAliases.json'
}

Node.js v18.7.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

should I do something more?

**Comment by SuperSandyman** [comment]
Odd coincidence, isn't it? I am suffering from the same problem. What should I do?

**Comment by Rakk4403** [comment]
@SuperSandyman looks like `raw files` missed. It could be generated from output files.

But I didn't and just using without add custom emojis
